### ISSUE TITLE
Website won't load.

### ISSUE THREAD

**Issue by valkyrienyanko** [mrpassiontea/mrpassiontea.github.io#1]
When I try to go to your website, I'm redirected to https://thegrove.dev and it says the page cannot be found.

**Comment by mrpassiontea** [comment]
Hi, @valkyrienyanko,
Thank you for your interest! Are you a part of the Discord group? Things fell off and we stopped the development of the website. However, there are thoughts of restarting the project. Are you interested in it?

**Comment by valkyrienyanko** [comment]
Not at the moment.
